import { SESClient, SendEmailCommand } from "@aws-sdk/client-ses";
import { StoreSnapshot } from "@foodwise/shared";
import { getAllStores, getStoreSnapshot } from "../utils/storeMetrics";

const ses = new SESClient({});
const REPORT_EMAIL = process.env.REPORT_EMAIL || "admin@foodwise.io";
const FROM_EMAIL = process.env.FROM_EMAIL || "reports@foodwise.io";

function formatCurrency(n: number): string {
  return `$${n.toFixed(2).replace(/\B(?=(\d{3})+(?!\d))/g, ",")}`;
}

function statusEmoji(status: string): string {
  if (status === "green") return "OK";
  if (status === "yellow") return "WATCH";
  return "ALERT";
}

function buildHtmlReport(
  snapshots: StoreSnapshot[],
  weekOf: string
): string {
  const totalSales = snapshots.reduce((s, snap) => s + snap.salesLast30d, 0);
  const avgFoodCost =
    snapshots.reduce((s, snap) => s + snap.foodCostPercentage, 0) /
    snapshots.length;
  const avgHealth =
    snapshots.reduce((s, snap) => s + snap.healthScore, 0) / snapshots.length;

  const storeRows = snapshots
    .sort((a, b) => b.healthScore - a.healthScore)
    .map(
      (s) => `
      <tr>
        <td style="padding:8px;border-bottom:1px solid #eee"><strong>${s.storeName}</strong></td>
        <td style="padding:8px;border-bottom:1px solid #eee;text-align:center">${s.healthScore}/100 [${statusEmoji(s.healthStatus)}]</td>
        <td style="padding:8px;border-bottom:1px solid #eee;text-align:center">${s.foodCostPercentage}% [${statusEmoji(s.foodCostStatus)}]</td>
        <td style="padding:8px;border-bottom:1px solid #eee;text-align:center">${s.wastePercentage}% [${statusEmoji(s.wasteStatus)}]</td>
        <td style="padding:8px;border-bottom:1px solid #eee;text-align:right">${formatCurrency(s.salesLast30d)}</td>
        <td style="padding:8px;border-bottom:1px solid #eee;text-align:center">${s.forecastAccuracy}%</td>
        <td style="padding:8px;border-bottom:1px solid #eee;text-align:center">${s.salesTrend === "up" ? "Up" : s.salesTrend === "down" ? "Down" : "Flat"}</td>
      </tr>`
    )
    .join("");

  // Generate key observations
  const observations: string[] = [];
  const redStores = snapshots.filter((s) => s.healthStatus === "red");
  if (redStores.length > 0) {
    observations.push(
      `<li><strong>Immediate attention:</strong> ${redStores.map((s) => s.storeName).join(", ")} ${redStores.length === 1 ? "has" : "have"} a health score below 50</li>`
    );
  }

  const decliningStores = snapshots.filter((s) => s.salesTrend === "down");
  if (decliningStores.length > 0) {
    observations.push(
      `<li><strong>Sales declining:</strong> ${decliningStores.map((s) => s.storeName).join(", ")}</li>`
    );
  }

  const highWaste = snapshots.filter((s) => s.wastePercentage > 5);
  if (highWaste.length > 0) {
    observations.push(
      `<li><strong>High waste:</strong> ${highWaste.map((s) => `${s.storeName} (${s.wastePercentage}%)`).join(", ")}</li>`
    );
  }

  const bestStore = snapshots.reduce((best, s) =>
    s.healthScore > best.healthScore ? s : best
  );
  observations.push(
    `<li><strong>Top performer:</strong> ${bestStore.storeName} with health score ${bestStore.healthScore}/100</li>`
  );

  return `
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="font-family:Arial,sans-serif;max-width:800px;margin:0 auto;padding:20px;color:#333">
  <h1 style="color:#2c5282">FoodWise Weekly Report</h1>
  <p style="color:#718096">Week of ${weekOf} | ${snapshots.length} store${snapshots.length !== 1 ? "s" : ""}</p>

  <div style="background:#f7fafc;border-radius:8px;padding:16px;margin:16px 0;display:flex;gap:24px">
    <div><strong>Total Sales (30d)</strong><br>${formatCurrency(totalSales)}</div>
    <div><strong>Avg Food Cost</strong><br>${Math.round(avgFoodCost * 10) / 10}%</div>
    <div><strong>Avg Health Score</strong><br>${Math.round(avgHealth)}/100</div>
  </div>

  <h2 style="color:#2c5282">Store Performance</h2>
  <table style="width:100%;border-collapse:collapse">
    <thead>
      <tr style="background:#edf2f7">
        <th style="padding:8px;text-align:left">Store</th>
        <th style="padding:8px;text-align:center">Health</th>
        <th style="padding:8px;text-align:center">Food Cost</th>
        <th style="padding:8px;text-align:center">Waste</th>
        <th style="padding:8px;text-align:right">Sales (30d)</th>
        <th style="padding:8px;text-align:center">Forecast Acc.</th>
        <th style="padding:8px;text-align:center">Sales Trend</th>
      </tr>
    </thead>
    <tbody>
      ${storeRows}
    </tbody>
  </table>

  <h2 style="color:#2c5282">Key Observations</h2>
  <ul>${observations.join("")}</ul>

  <hr style="border:none;border-top:1px solid #e2e8f0;margin:24px 0">
  <p style="color:#a0aec0;font-size:12px">Generated by FoodWise Platform | ${new Date().toISOString()}</p>
</body>
</html>`;
}

function buildTextReport(snapshots: StoreSnapshot[], weekOf: string): string {
  const lines: string[] = [
    `FOODWISE WEEKLY REPORT — Week of ${weekOf}`,
    `${snapshots.length} store(s)`,
    "",
    "STORE PERFORMANCE:",
    "-".repeat(80),
  ];

  for (const s of snapshots.sort((a, b) => b.healthScore - a.healthScore)) {
    lines.push(
      `${s.storeName}: Health ${s.healthScore}/100 | Food Cost ${s.foodCostPercentage}% | Waste ${s.wastePercentage}% | Sales ${formatCurrency(s.salesLast30d)} | Trend: ${s.salesTrend}`
    );
  }

  return lines.join("\n");
}

export const handler = async (): Promise<{
  statusCode: number;
  body: string;
}> => {
  try {
    const stores = await getAllStores();

    if (stores.length === 0) {
      console.log("No stores found, skipping weekly report");
      return { statusCode: 200, body: "No stores — report skipped" };
    }

    const snapshots = await Promise.all(stores.map(getStoreSnapshot));

    const now = new Date();
    const weekOf = now.toISOString().split("T")[0];

    const htmlBody = buildHtmlReport(snapshots, weekOf);
    const textBody = buildTextReport(snapshots, weekOf);

    await ses.send(
      new SendEmailCommand({
        Source: FROM_EMAIL,
        Destination: { ToAddresses: [REPORT_EMAIL] },
        Message: {
          Subject: {
            Data: `FoodWise Weekly Report — ${weekOf}`,
          },
          Body: {
            Html: { Data: htmlBody },
            Text: { Data: textBody },
          },
        },
      })
    );

    console.log(`Weekly report sent to ${REPORT_EMAIL}`);
    return {
      statusCode: 200,
      body: JSON.stringify({
        message: "Weekly report sent",
        stores: snapshots.length,
        sentTo: REPORT_EMAIL,
      }),
    };
  } catch (err) {
    console.error("GenerateWeeklyReport error:", err);
    return {
      statusCode: 500,
      body: JSON.stringify({ message: "Failed to generate weekly report" }),
    };
  }
};
